# netlify.toml
[build]
  # we have no build step
  command = ""
  # these are the folders we want Netlify to publish
  publish = "public"
  functions = "functions"

# redirect the two friendly URLs to your functions
[[redirects]]
  from    = "/encrypt"
  to      = "/.netlify/functions/encrypt"
  status  = 200
  methods = ["POST"]

[[redirects]]
  from    = "/decrypt"
  to      = "/.netlify/functions/decrypt"
  status  = 200
  methods = ["POST"]
